#!/usr/bin/env php
<?php
/**
 * Woski - A PHP framework
 * @author Clinton Nzedimma <clinton@woski.xyz>
 *
 * @package Woski

 * This bootstraps the CLI
 **/
require 'core/woski.php';
$cli = new Woski\Cli\Cli();
